const PropertyData = [
  {
    id: 1,
    image: "/property-1.jpg",
    title: "Modern Family Home",
    desc: "Contemporary home with stylish design and functional living spaces.",
    price: "85,000",
  },
  {
    id: 2,
    image: "/property-2.jpg",
    title: "Spacious Luxury Residence",
    desc: "Expansive residence featuring elegant finishes and abundant natural lighting.",
    price: "92,000",
  },
  {
    id: 3,
    image: "/property-3.jpg",
    title: "Urban Contemporary Villa",
    desc: "Modern villa designed for comfort, privacy, and architectural excellence.",
    price: "110,000",
  },
  {
    id: 4,
    image: "/property-4.jpg",
    title: "Elegant Suburban House",
    desc: "Refined suburban property with open-plan interiors and premium materials.",
    price: "78,500",
  },
  {
    id: 5,
    image: "/property-5.jpg",
    title: "Minimalist Smart Home",
    desc: "Sleek smart home integrating technology with minimalist aesthetics.",
    price: "125,000",
  },
  {
    id: 6,
    image: "/property-6.jpg",
    title: "Classic Brick Mansion",
    desc: "Timeless brick mansion combining traditional charm with modern upgrades.",
    price: "140,000",
  },
  {
    id: 7,
    image: "/property-7.jpg",
    title: "Luxury Penthouse Suite",
    desc: "High-end penthouse offering panoramic views and premium interior finishes.",
    price: "160,000",
  },
  {
    id: 8,
    image: "/property-8.jpg",
    title: "Cozy Modern Cottage",
    desc: "Warm and inviting cottage with contemporary detailing and natural textures.",
    price: "69,000",
  },
  {
    id: 9,
    image: "/property-9.jpg",
    title: "Waterfront Executive Home",
    desc: "Exclusive waterfront property designed for luxury and serenity.",
    price: "185,000",
  },
  {
    id: 10,
    image: "/property-10.jpg",
    title: "Contemporary Glass Villa",
    desc: "Architectural masterpiece featuring glass facades and open living concepts.",
    price: "210,000",
  },
  {
    id: 11,
    image: "/property-11.jpg",
    title: "Family Comfort Estate",
    desc: "Spacious estate tailored for family living with landscaped surroundings.",
    price: "97,000",
  },
  {
    id: 12,
    image: "/property-12.jpg",
    title: "Premium Urban Apartment",
    desc: "Modern city apartment designed for professionals seeking comfort and style.",
    price: "73,500",
  },
];

export default PropertyData;
